language: php
php:
- '7.2'
branches:
  only:
  - master
#addons:
#  mariadb: '10.2'
env:
# in sequence :
# get the directory name after the sign "-"
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags" displays the last tag's shortname
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags" displays the last tag's first line
# "git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags" displays the last tag's 3d line and following ones
>
  - GLPI_PLUGIN_NAME=`echo $TRAVIS_BUILD_DIR | sed -e 's/^.*-//'`
    TRAVIS_TAG=`git for-each-ref --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags`
    RELEASE_NAME=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags`
    RELEASE_BODY=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)' refs/tags`
install: true
script: true
after_success:
- tar --transform "s%^%$GLPI_PLUGIN_NAME/%" --show-transformed -zcvf $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz ajax front inc locales sql *.png *.xml *.php  LICENSE README.md
deploy:
  provider: releases
  token:
    secure: FQT1uKbO+LN8T3bfUbAD5guBsI4byRMSwWOTSA60vr306neIC9PLzmAxeZYHNz42x/Ph+0fenpo7KYbDTo2OFAx60KXCdmBMFE6XFhHoNJnS3XFDgCzoRNAZMrtpDdexiIGafi693gkxNw4G1LsUmWHcFvt6p38ZjIr2dG+GPobknGY1zv8TH9H9pba7Vwp0MVjefujMZcsXGSZ/mXVIAMOQrQBGNVcj5d1NynAGTc4yoayowCP9CAGZERVCU9xpysLbeGmJjnIDSNWLEMndAOMZp+vzuX10uN0FQ/MIdGegvGyStfIWmO57IN4mnMuxl/6ukDWDu+MmeVWF1Ygk7MNXMILKHUgsnVBmp0tzHJbdynHotO7QE0Da24L3nfBnVrrKFs5ni6LJ6VRGj9YTkp3KGbnY1sCOR9FIoF3QwY7W4k4pGrwZ55+ECDQqRdumBDhUkqmCHyH9NRw1muYZ7gqHQSLm0tYwRQ9sH1/Ty4qQm1uNLNcNIbyrTCYIW4+fq/5FrgQ0Uk9DjznTiWnIKWmCBduVX/ekrYAHRZdkNlTMNEubVtGur2T/B51rYkGeNHjifWwj0NUU7aCNcPfX2Zy8/6yi7qsns/xTkYURusT7qRkf9zKN0nuGKXNY+KDtWYJCa+egjLAeS7D1JpKfIkcIurtTJnLuz3EPmcU1vw0=
  skip_cleanup: true
  file: $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz
  name: $RELEASE_NAME
  release_notes: $RELEASE_BODY
  prerelease: false
  on:
    repo: ericferon/glpi-$GLPI_PLUGIN_NAME
    tags: true
